branches:
  - main
  - next
  - name: develop
    prerelease: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets: 
        - 'CHANGELOG.md'
