branches:
  - main
  - name: next
    prerelease: rc
  - name: beta
    prerelease: beta
plugins:
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
