branches:
  - main
  - name: develop
    prerelease: beta
  - name: next
    prerelease: rc
  - name: alpha
    prerelease: alpha
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  - '@semantic-release/git'
