name: NPM Publish
on:
  push:
    tags:
      - 'v*'
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Pack all
        run: yarn pack:all
      - name: Publish To NPM
        run: yarn publish:all
