name: Semantic Release
on:
  push:
    branches:
      - 'main'
      - 'next'
      - 'develop'
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Release
        run: yarn semantic-release
