# TODO: refactor this workflow to trigger after ci job has finished
name: Build and Semantic Release
on:
  push:
    branches:
      - 'main'
      - 'next'
      - 'develop'
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build_release:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Release
        run: npm run semantic-release
